//File Generated By TelemetryFromXTCE.py

#ifndef ADCSTELEMETRYCONTAINER_H_
#define ADCSTELEMETRYCONTAINER_H_

#include "TelemetryContainer.h"

#define ADCS_CONTAINER_SIZE  35

class ADCSTelemetryContainer : public TelemetryContainer
{
protected:
unsigned char telemetry[ADCS_CONTAINER_SIZE];

public:
    virtual int size();
    virtual unsigned char * getArray();

    char getStatus();
    void setStatus(char var);

    char getBootCounter();
    void setBootCounter(char var);

    long getResetCause();
    void setResetCause(long var);

    unsigned long getUptime();
    void setUptime(unsigned long var);

    unsigned long getTotalUptime();
    void setTotalUptime(unsigned long var);

    char getVersionNumber();
    void setVersionNumber(char var);

    short getMCUTemp();
    void setMCUTemp(short var);

    bool getINAStatus();
    void setINAStatus(bool var);

    bool getTMPStatus();
    void setTMPStatus(bool var);

    bool getTorquerZStatus();
    void setTorquerZStatus(bool var);

    bool getTorquerYStatus();
    void setTorquerYStatus(bool var);

    bool getTorquerXStatus();
    void setTorquerXStatus(bool var);

    short getVoltage();
    void setVoltage(short var);

    short getCurrent();
    void setCurrent(short var);

    short getTemperature();
    void setTemperature(short var);

    short getTorquerZCurrent();
    void setTorquerZCurrent(short var);

    short getTorquerYCurrent();
    void setTorquerYCurrent(short var);

    short getTorquerXCurrent();
    void setTorquerXCurrent(short var);

    short getTorquerZVoltage();
    void setTorquerZVoltage(short var);

    short getTorquerYVoltage();
    void setTorquerYVoltage(short var);

    short getTorquerXVoltage();
    void setTorquerXVoltage(short var);

};

#endif /* ADCSTELEMETRYCONTAINER_H_ */
