//File Generated By TelemetryFromXTCE.py

#include "ADCSTelemetryContainer.h"

int ADCSTelemetryContainer::size()
{
    return ADCS_CONTAINER_SIZE;
}

unsigned char* ADCSTelemetryContainer::getArray()
{
    return &telemetry[0];
}

char ADCSTelemetryContainer::getStatus()
{
    return telemetry[0];
}
void ADCSTelemetryContainer::setStatus(char uchar)
{
    telemetry[0] = uchar;
}
char ADCSTelemetryContainer::getBootCounter()
{
    return telemetry[1];
}
void ADCSTelemetryContainer::setBootCounter(char uchar)
{
    telemetry[1] = uchar;
}
long ADCSTelemetryContainer::getResetCause()
{
    unsigned long ulong;
    ((unsigned char *)&ulong)[2] = telemetry[2];
    ((unsigned char *)&ulong)[1] = telemetry[3];
    ((unsigned char *)&ulong)[0] = telemetry[4];
    return ulong;
}
void ADCSTelemetryContainer::setResetCause(long ulong)
{
    telemetry[2] = ((unsigned char *)&ulong)[2];
    telemetry[3] = ((unsigned char *)&ulong)[1];
    telemetry[4] = ((unsigned char *)&ulong)[0];
}
unsigned long ADCSTelemetryContainer::getUptime()
{
    unsigned long ulong;
    ((unsigned char *)&ulong)[3] = telemetry[5];
    ((unsigned char *)&ulong)[2] = telemetry[6];
    ((unsigned char *)&ulong)[1] = telemetry[7];
    ((unsigned char *)&ulong)[0] = telemetry[8];
    return ulong;
}
void ADCSTelemetryContainer::setUptime(unsigned long ulong)
{
    telemetry[5] = ((unsigned char *)&ulong)[3];
    telemetry[6] = ((unsigned char *)&ulong)[2];
    telemetry[7] = ((unsigned char *)&ulong)[1];
    telemetry[8] = ((unsigned char *)&ulong)[0];
}
unsigned long ADCSTelemetryContainer::getTotalUptime()
{
    unsigned long ulong;
    ((unsigned char *)&ulong)[3] = telemetry[9];
    ((unsigned char *)&ulong)[2] = telemetry[10];
    ((unsigned char *)&ulong)[1] = telemetry[11];
    ((unsigned char *)&ulong)[0] = telemetry[12];
    return ulong;
}
void ADCSTelemetryContainer::setTotalUptime(unsigned long ulong)
{
    telemetry[9] = ((unsigned char *)&ulong)[3];
    telemetry[10] = ((unsigned char *)&ulong)[2];
    telemetry[11] = ((unsigned char *)&ulong)[1];
    telemetry[12] = ((unsigned char *)&ulong)[0];
}
char ADCSTelemetryContainer::getVersionNumber()
{
    return telemetry[13];
}
void ADCSTelemetryContainer::setVersionNumber(char uchar)
{
    telemetry[13] = uchar;
}
short ADCSTelemetryContainer::getMCUTemp()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[14];
    ((unsigned char *)&ushort)[0] = telemetry[15];
    return ushort;
}
void ADCSTelemetryContainer::setMCUTemp(short ushort)
{
    telemetry[14] = ((unsigned char *)&ushort)[1];
    telemetry[15] = ((unsigned char *)&ushort)[0];
}
bool ADCSTelemetryContainer::getINAStatus()
{
    return ((telemetry[16] & 0x80) != 0);
}
void ADCSTelemetryContainer::setINAStatus(bool bval)
{
    telemetry[16] &= (~0x80);
    telemetry[16] |= bval ? 0x80 : 0x00;
}
bool ADCSTelemetryContainer::getTMPStatus()
{
    return ((telemetry[16] & 0x40) != 0);
}
void ADCSTelemetryContainer::setTMPStatus(bool bval)
{
    telemetry[16] &= (~0x40);
    telemetry[16] |= bval ? 0x40 : 0x00;
}
bool ADCSTelemetryContainer::getTorquerZStatus()
{
    return ((telemetry[16] & 0x20) != 0);
}
void ADCSTelemetryContainer::setTorquerZStatus(bool bval)
{
    telemetry[16] &= (~0x20);
    telemetry[16] |= bval ? 0x20 : 0x00;
}
bool ADCSTelemetryContainer::getTorquerYStatus()
{
    return ((telemetry[16] & 0x10) != 0);
}
void ADCSTelemetryContainer::setTorquerYStatus(bool bval)
{
    telemetry[16] &= (~0x10);
    telemetry[16] |= bval ? 0x10 : 0x00;
}
bool ADCSTelemetryContainer::getTorquerXStatus()
{
    return ((telemetry[16] & 0x08) != 0);
}
void ADCSTelemetryContainer::setTorquerXStatus(bool bval)
{
    telemetry[16] &= (~0x08);
    telemetry[16] |= bval ? 0x08 : 0x00;
}
short ADCSTelemetryContainer::getVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[17];
    ((unsigned char *)&ushort)[0] = telemetry[18];
    return ushort;
}
void ADCSTelemetryContainer::setVoltage(short ushort)
{
    telemetry[17] = ((unsigned char *)&ushort)[1];
    telemetry[18] = ((unsigned char *)&ushort)[0];
}
short ADCSTelemetryContainer::getCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[19];
    ((unsigned char *)&ushort)[0] = telemetry[20];
    return ushort;
}
void ADCSTelemetryContainer::setCurrent(short ushort)
{
    telemetry[19] = ((unsigned char *)&ushort)[1];
    telemetry[20] = ((unsigned char *)&ushort)[0];
}
short ADCSTelemetryContainer::getTemperature()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[21];
    ((unsigned char *)&ushort)[0] = telemetry[22];
    return ushort;
}
void ADCSTelemetryContainer::setTemperature(short ushort)
{
    telemetry[21] = ((unsigned char *)&ushort)[1];
    telemetry[22] = ((unsigned char *)&ushort)[0];
}
short ADCSTelemetryContainer::getTorquerZCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[23];
    ((unsigned char *)&ushort)[0] = telemetry[24];
    return ushort;
}
void ADCSTelemetryContainer::setTorquerZCurrent(short ushort)
{
    telemetry[23] = ((unsigned char *)&ushort)[1];
    telemetry[24] = ((unsigned char *)&ushort)[0];
}
short ADCSTelemetryContainer::getTorquerYCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[25];
    ((unsigned char *)&ushort)[0] = telemetry[26];
    return ushort;
}
void ADCSTelemetryContainer::setTorquerYCurrent(short ushort)
{
    telemetry[25] = ((unsigned char *)&ushort)[1];
    telemetry[26] = ((unsigned char *)&ushort)[0];
}
short ADCSTelemetryContainer::getTorquerXCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[27];
    ((unsigned char *)&ushort)[0] = telemetry[28];
    return ushort;
}
void ADCSTelemetryContainer::setTorquerXCurrent(short ushort)
{
    telemetry[27] = ((unsigned char *)&ushort)[1];
    telemetry[28] = ((unsigned char *)&ushort)[0];
}
short ADCSTelemetryContainer::getTorquerZVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[29];
    ((unsigned char *)&ushort)[0] = telemetry[30];
    return ushort;
}
void ADCSTelemetryContainer::setTorquerZVoltage(short ushort)
{
    telemetry[29] = ((unsigned char *)&ushort)[1];
    telemetry[30] = ((unsigned char *)&ushort)[0];
}
short ADCSTelemetryContainer::getTorquerYVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[31];
    ((unsigned char *)&ushort)[0] = telemetry[32];
    return ushort;
}
void ADCSTelemetryContainer::setTorquerYVoltage(short ushort)
{
    telemetry[31] = ((unsigned char *)&ushort)[1];
    telemetry[32] = ((unsigned char *)&ushort)[0];
}
short ADCSTelemetryContainer::getTorquerXVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[33];
    ((unsigned char *)&ushort)[0] = telemetry[34];
    return ushort;
}
void ADCSTelemetryContainer::setTorquerXVoltage(short ushort)
{
    telemetry[33] = ((unsigned char *)&ushort)[1];
    telemetry[34] = ((unsigned char *)&ushort)[0];
}
